app:
  name: AroundYoga
  host: aroundyoga-sheng-step6.herokuapp.com/
  local_host: localhost:3000
facebook:
  app_id: 1389256591289066
  app_secret: 415ba8552d6a1f2e2ace026eed0fff57    
twitter:
  app_id: fkwAmMQnGTo4AG4pxdf0GA
  app_secret: cvkyGQWIMIQfhNPB0qOt4wMpE3epuhYFaVBr2cKs
google:
  app_id: 354851137012-rir0ovgnpu7b20g8h69opaat13j2ovhj.apps.googleusercontent.com
  app_secret: 7t_ZmOjTiq_Q5qCIyjAn4avu
smtp:
  tls: true
  from: user <user@gmail.com>
  address: smtp.gmail.com
  port: 25
  domain: gmail.com
  authentication: plain
  user_name: aroundyoga@gmail.com
  password: dragon9(
exceptions:
  recipients: [user+exceptions@gmail.com]
  sender: "user <user@gmail.com>"